### ISSUE TITLE
When I have started my app using your package its running on both https and http connections.

### ISSUE THREAD

**Issue by AnjaniKumar15** [ADAIN/meteor-https#1]
When I have started my app using your package its running on both https and http connections.
I have used meteor-https and force-ssl both but its running on https://localhost:3000  and also on https://localhost:8443..

**Comment by ADAIN** [comment]
Hi.
I was updated package version to 1.1.0
Try this.
`meteor remove force-ssl`
`meteor update adain:meteor-https`
`export FORCE_SSL=1`
Thank you.

**Comment by AnjaniKumar15** [comment]
Thanks Its working now..
