### ISSUE TITLE
Not able to run my meteor project using your package and with foreverjs on server side. Is your package also works with foreverjs?

### ISSUE THREAD

**Issue by AnjaniKumar15** [ADAIN/meteor-https#2]
Not able to run my meteor project using your package and with **foreverjs** on **server side**.
Is your package also works with **foreverjs**?

**Comment by ADAIN** [comment]
Sure.
If you use linux, make script file like this.

run.sh

```
#!/usr/bin/env bash

export ROOT_URL=https://localhost:8443
export USE_HTTPS=1
export SSL_KEY_PATH=~/dev/ssl-test/server.key
export SSL_CERT_PATH=~/dev/ssl-test/cert.pem
export SSL_PORT=8443
export SSL_TARGET_IP=127.0.0.1
export SSL_TARGET_PORT=3000
export FORCE_SSL=1
export PORT=3000

forever main.js
```

`chmod +x ./run.sh`
`./run.sh`

Before run this script, you have to build your meteor project with build command.
`meteor build ../out`
