### ISSUE TITLE
Error handler is necessary for proxy

### ISSUE THREAD

**Issue by bladerunner2020** [ADAIN/meteor-https#4]
Adding **uncaughtException** handler is not a best way to handle error. This handler will catch other uncaught exceptions as well and this is not correct.

Adding proxy error handler would solve this and makes **NEVER_DIE** flag not necessary...

```js
  const proxy = httpProxy.createProxyServer(options).listen(SSL_PORT);
  proxy.on('error', (err, req, res) => {
    // console.error(err);
    res.writeHead(500, {
      'Content-Type': 'text/plain'
    });

    res.end('Something went wrong. And we are reporting a custom error message.');
  });
``

**Comment by ADAIN** [comment]
Thanks for your contributing. I applied it.

By the way, after meteor CLI updated to 2.0, I can't sign in with my username.
So this package can no longer be updated.

====================================================================
If you want to use this package with update.

OPTION 1
Add this package to your METEOR_PACKAGE_DIRS (Environment variable) folder.
Default value of METEOR_PACKAGE_DIRS is "packages"

OPTION 2
Rename this package with your username and upload it to the package server.
[Publish CLI document path.](https://docs.meteor.com/commandline.html#meteorpublish)
